### ISSUE TITLE
mod_mosquitto cannot be loaded by FreeSWITCH

### ISSUE THREAD

**Issue by ginkel** [freeswitch/mod_mosquitto#16]
Hello everyone,

while evaluation options to connect our FreeSWITCH instance to MQTT I came across mod_mosquitto. Unfortunately, I haven't been able to successfully load it into FreeSWITCH 1.10.10. Our FreeSWITCH deployment is using a Debian 11 based Docker image that installs FreeSWITCH using the official Debian packages. I temporarily published the Docker build at: https://github.com/tgbyte/docker-freeswitch.

I am using the following `Makefile` (based on https://developer.signalwire.com/freeswitch/FreeSWITCH-Explained/Community/Contributing-Code/Creating-New-Modules/#using-development-headers-libfreeswitch-dev) to build the module against libfreeswitch-dev instead of compiling FreeSWITCH from scratch: https://github.com/tgbyte/docker-freeswitch/blob/main/Makefile

**Describe the bug**
The built module cannot be loaded by FreeSWITCH (despite being present in `/usr/lib/freeswitch/mod`):

```
2023-11-13 22:10:38.469896 0.00% [CRIT] switch_loadable_module.c:1754 Error Loading module /usr/lib/freeswitch/mod/mod_mosquitto.so
**Module load routine returned an error**
```

Unfortunately, increasing FreeSWITCH's log level did not lead to more information. Executing `ld` on the module's `.so` does not show any dependency issues.

Any ideas?

Thanks,
Thilo

**Comment by NormB** [comment]
Sorry for the delay. Will look into this even though I expect that you've "moved on".

**Comment by ginkel** [comment]
Thanks for getting back to me! I am currently using baresip to signal calls via mqtt, but getting this module to work would be really nice.

Let me know if you need any further details!

**Comment by NormB** [comment]
Just following up again. I've reinstalled the module on a clean system and have had no problem getting the module to load. The problem you experienced perhaps has something to do with the particular way you have installed FreeSWITCH and compiled the module.

Closing this issue. Please open a new issue with a bit more detail if you are still having problems.

Norm
